import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const source = new URL('../server/schema.sql', import.meta.url)
const destination = new URL('../database/schema.sql', import.meta.url)
const header = `-- Generated by npm run db:schema from server/schema.sql.
-- Contains structure only; no letters or credentials are exported.
CREATE DATABASE IF NOT EXISTS violet_garden
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE violet_garden;

`

mkdirSync(new URL('../database/', import.meta.url), { recursive: true })
writeFileSync(destination, header + readFileSync(source, 'utf8').replaceAll('\r\n', '\n'))
console.log('Generated database/schema.sql (structure only).')
